# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.0
xcode_sdk: iphonesimulator10.0

script:
- set -o pipefail && xcodebuild test -workspace Example/RxEureka.xcworkspace -scheme RxEureka-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
